//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FishingJoy
//  @ File Name : StaticDate.h
//  @ Date : 2017/9/24
//  @ Author : mjm
//
//


#if !defined(_STATICDATE_H)
#define _STATICDATE_H


class StaticDate {
public:
	StaticData * shareStaticData();
	void purge();
	int intValueForKey(std::string key);
	char stringValueFromKey(std::string key);
	float floatValueFromKey(std::string key);
	bool boooleanFromKey(std::string key);
	cocos2d::CCPoint pointFromKey(std::string key);
	cocos2d::CCRect rectFromKey(std::string key);
	cocos2d::CCSize sizeFromKey(std::string key);
protected:
	cocos2d::CCDictionary _dictionary;
	std::string _staticFileName;
	bool init();
private:
	~StaticData();
	StaticData();
};

#endif  //_STATICDATE_H
